apiVersion: v1
kind: Service
metadata:
  name: release-agent
  namespace: release-agent
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app: release-agent
spec:
  type: ClusterIP

  selector:
    app: release-agent

  ports:
    - name: http
      port: 80
      targetPort: 8080